urls.py
##############################################################################
#
#    OSIS stands for Open Student Information System. It's an application
#    designed to manage the core business of higher education institutions,
#    such as universities, faculties, institutes and professional schools.
#    The core business involves the administration of students, teachers,
#    courses, programs and so on.
#
#    Copyright (C) 2015-2022 Université catholique de Louvain (http://www.uclouvain.be)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
# ##############################################################################
from django.conf import settings

from osis_common.utils.file_router import FileRouter

app_name = 'admission'

file_router = FileRouter()
urlpatterns = file_router('admission/views')

if settings.DEBUG:
    import logging

    logger = logging.getLogger(__name__)
    logger.debug("\n" + file_router.debug(urlpatterns))

models/task.py
# ##############################################################################
#
#    OSIS stands for Open Student Information System. It's an application
#    designed to manage the core business of higher education institutions,
#    such as universities, faculties, institutes and professional schools.
#    The core business involves the administration of students, teachers,
#    courses, programs and so on.
#
#    Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
# ##############################################################################
from django.db import models

from django.utils.translation import gettext_lazy as _

from admission.models.base import BaseAdmissionQuerySet


def admission_export_path(task: 'AdmissionTask', filename: str):
    """Return the file upload directory path."""
    return 'admission/{}/{}/exports/{}'.format(
        task.admission.candidate.uuid,
        task.admission.uuid,
        filename,
    )


class AdmissionTaskQuerySet(BaseAdmissionQuerySet):
    training_field_name = 'admission__doctorate_id'


class AdmissionTaskManager(models.Manager.from_queryset(AdmissionTaskQuerySet)):
    pass


class AdmissionTask(models.Model):
    class TaskType(models.TextChoices):
        ARCHIVE = 'ARCHIVE', _('PDF Export')
        GENERAL_RECAP = 'GENERAL_RECAP', _('PDF recap for a general education admission')
        CONTINUING_RECAP = 'CONTINUING_RECAP', _('PDF recap for a continuing education admission')
        DOCTORATE_RECAP = 'DOCTORATE_RECAP', _('PDF recap for a doctorate education admission')
        GENERAL_MERGE = 'GENERAL_MERGE', _('Merging of each document field of a general proposition into one PDF')
        CONTINUING_MERGE = 'CONTINUING_MERGE', _(
            'Merging of each document field of a continuing proposition into one PDF',
        )
        DOCTORATE_MERGE = 'DOCTORATE_MERGE', _('Merging of each document field of a doctorate proposition into one PDF')
        GENERAL_FOLDER = 'GENERAL_FOLDER', _('Analysis folder for a general education admission')
        CONTINUING_FOLDER = 'CONTINUING_FOLDER', _('Analysis folder for a continuing education admission')
        DOCTORATE_FOLDER = 'DOCTORATE_FOLDER', _('Analysis folder for a doctorate education admission')

    task = models.ForeignKey(
        'osis_async.AsyncTask',
        on_delete=models.CASCADE,
    )
    admission = models.ForeignKey(
        'admission.BaseAdmission',
        on_delete=models.CASCADE,
    )
    type = models.CharField(
        choices=TaskType.choices,
        max_length=20,
    )

    objects = AdmissionTaskManager()

api/views/continuing_education.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################

from django.http import Http404
from rest_framework.generics import RetrieveAPIView

from admission.api import serializers
from admission.api.schema import BetterChoicesSchema
from ddd.logic.formation_catalogue.formation_continue.commands import RecupererInformationsSpecifiquesQuery
from ddd.logic.formation_catalogue.formation_continue.domain.validator.exceptions import (
    InformationsSpecifiquesNonTrouveesException,
)
from infrastructure.messages_bus import message_bus_instance


class RetrieveContinuingEducationSpecificInformationView(RetrieveAPIView):
    name = 'retrieve-continuing-education-specific-information'
    schema = BetterChoicesSchema()
    filter_backends = []
    serializer_class = serializers.InformationsSpecifiquesFormationContinueDTOSerializer

    def get_serializer_context(self):
        context = super().get_serializer_context()

        context['acronym'] = self.kwargs.get('sigle')
        context['academic_year'] = self.kwargs.get('annee')

        return context

    def get_object(self):
        try:
            return message_bus_instance.invoke(
                RecupererInformationsSpecifiquesQuery(
                    sigle_formation=self.kwargs['sigle'],
                    annee=self.kwargs['annee'],
                )
            )
        except InformationsSpecifiquesNonTrouveesException:
            raise Http404

views/list.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.exceptions import NON_FIELD_ERRORS
from django.utils.functional import cached_property
from django.utils.translation import gettext as _
from django.views.generic import ListView
from django.views.generic.edit import FormMixin

from admission.constants import DEFAULT_PAGINATOR_SIZE
from admission.ddd.admission.commands import ListerToutesDemandesQuery
from admission.forms.admission.filter import AllAdmissionsFilterForm
from admission.utils import add_messages_into_htmx_response
from admission.views import ListPaginator
from base.views.common import display_error_messages
from infrastructure.messages_bus import message_bus_instance
from osis_common.utils.htmx import HtmxMixin

__all__ = [
    "AdmissionList",
]


class BaseAdmissionList(LoginRequiredMixin, PermissionRequiredMixin, HtmxMixin, FormMixin, ListView):
    raise_exception = True
    filtering_query_class = None
    htmx_template_name = None
    parameters_cache_timeout = None
    result_cache_timeout = 60 * 60 * 24  # 1 day

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.form = None
        self.filters = {}

    @property
    def cache_key(self):
        return f"cache_filter_{self.request.user.id}_{self.request.path}"

    @classmethod
    def cache_key_for_result(cls, user_id):
        return f"cache_filter_result_{user_id}"

    @staticmethod
    def htmx_render_form_errors(request, form):
        """Display the form errors through the django messages."""
        display_error_messages(
            request=request,
            messages_to_display=[
                '{} - {}'.format(
                    form.fields.get(field_name).label if field_name != NON_FIELD_ERRORS else _('General'),
                    ' '.join(errors),
                )
                for field_name, errors in form.errors.items()
            ],
        )

    def get_context_data(self, **kwargs):
        kwargs['form'] = self.form
        kwargs['filter_form'] = self.form
        kwargs['htmx_template_name'] = self.htmx_template_name
        kwargs['default_form_values'] = {field.name: field.initial for field in self.form if field.initial}
        kwargs['now'] = datetime.datetime.now()
        return super().get_context_data(**kwargs)

    def get_paginate_by(self, queryset):
        if self.form.is_valid() and self.form.cleaned_data.get('taille_page'):
            return self.form.cleaned_data.get('taille_page')
        return DEFAULT_PAGINATOR_SIZE

    def additional_command_kwargs(self):
        return {}

    @cached_property
    def query_params(self):
        return self.request.GET or cache.get(self.cache_key)

    def get_form_kwargs(self):
        return {
            'user': self.request.user,
            'data': self.query_params,
            'load_labels': not self.request.htmx,
        }

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()

        if not self.form.is_valid():
            self.object_list = []
            response = self.form_invalid(form=self.form)
            if self.request.htmx:
                self.htmx_render_form_errors(self.request, self.form)
                add_messages_into_htmx_response(request=self.request, response=response)
            return response

        if self.request.GET:
            cache.set(self.cache_key, self.request.GET, timeout=self.parameters_cache_timeout)

        self.filters = self.form.cleaned_data

        self.filters.pop('liste_travail', None)

        if self.query_params:
            # Add page number to kwargs to pass it to the paginator
            self.kwargs['page'] = self.query_params.get('page')

            # Order the queryset if specified
            ordering_field = self.query_params.get('o')

            if ordering_field:
                self.filters['tri_inverse'] = ordering_field[0] == '-'
                self.filters['champ_tri'] = ordering_field.lstrip('-')

        response = super().get(request, *args, **kwargs)

        if self.request.GET:
            cache.set(
                self.cache_key_for_result(user_id=self.request.user.id),
                self.object_list.sorted_elements,
                timeout=self.result_cache_timeout,
            )

        return response

    def get_queryset(self):
        return message_bus_instance.invoke(
            self.filtering_query_class(
                **self.filters,
                **self.additional_command_kwargs(),
            )
        )


class AdmissionList(BaseAdmissionList):
    template_name = 'admission/list/list_all.html'
    htmx_template_name = 'admission/list/list_all_block.html'
    permission_required = 'admission.view_enrolment_applications'
    filtering_query_class = ListerToutesDemandesQuery
    form_class = AllAdmissionsFilterForm
    urlpatterns = 'all-list'
    paginator_class = ListPaginator

    def additional_command_kwargs(self):
        return {
            'demandeur': self.request.user.person.uuid,
        }

templates/admission/continuing_education/checklist_menu.html
{% load admission strings %}
{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

<ul id="checklist-menu" class="list-group">
  {% for checklist_item_name, checklist_item in original_admission.checklist.initial|get_ordered_checklist_items_continuing_education %}
    {% with initial=original_admission.checklist.initial|get_item:checklist_item_name current=original_admission.checklist.current|get_item:checklist_item_name %}
      {% firstof current.statut initial.statut as statut %}
      <li
          class="list-group-item{% if forloop.first %} active{% endif %}"
          href="#{{ checklist_item_name }}"
      >
        <div
            data-toggle="tab"
            href="#{{ checklist_item_name }}"
        >
          <a>
            {% include 'admission/continuing_education/checklist_menu_item_status.html' with statut=statut extra=current.extra item_name=checklist_item_name %}
            {{ checklist_tabs|get_item:checklist_item_name }}
            {% if checklist_additional_icons and checklist_additional_icons|get_item_or_none:checklist_item_name %}
              {% include 'admission/continuing_education/checklist_menu_item_additional_icon.html' with item_name=checklist_item_name additional_icon=checklist_additional_icons|get_item:checklist_item_name %}
            {% endif %}
          </a>
        </div>
      </li>
    {% endwith %}
  {% endfor %}
</ul>

templates/admission/continuing_education/checklist_menu_item_additional_icon.html
{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

<i
    hx-swap-oob="outerHTML"
    id="checklist-menu-item-additional-icon-{{ item_name }}"
    {% if additional_icon %}
    class="{{ additional_icon }}"
    {% endif %}
>
</i>

templates/admission/continuing_education/checklist_menu_item_status.html
{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

<span id="checklist-menu-item-status-{{ item_name }}" hx-swap-oob="true">
  {% if statut == 'INITIAL_NON_CONCERNE' %}
    <i class="fas fa-xmark text-muted"></i>
  {% elif statut == 'GEST_EN_COURS' %}
    {% if extra.en_cours == 'taken_in_charge' %}
      <i class="fas fa-pencil text-warning"></i>
    {% elif extra.en_cours == 'fac_approval' %}
      <i class="fas fa-circle-arrow-right text-success"></i>
    {% elif extra.en_cours == 'on_hold' %}
      <i class="fas fa-circle-stop text-info"></i>
    {% elif extra.en_cours == 'to_validate' %}
      <i class="fas fa-list-check text-info"></i>
    {% else %}
      <i class="fas fa-pencil text-warning"></i>
    {% endif %}
  {% elif statut == 'GEST_BLOCAGE' %}
    <i class="fas fa-circle-stop text-danger"></i>
  {% elif statut == 'GEST_BLOCAGE_ULTERIEUR' %}
    <i class="fas fa-circle-arrow-right text-info"></i>
  {% elif statut == 'GEST_REUSSITE' or statut == 'SYST_REUSSITE' %}
    <i class="fas fa-check text-success"></i>
  {% else %}
    <i aria-hidden="true"></i>
  {% endif %}
</span>

templates/admission/continuing_education/list.html
{% extends "admission/list/base.html" %}
{% load bootstrap3 i18n osis_role pagination static enums %}

{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2024 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

{% block breadcrumb %}
  <li>
    <a href="{% url 'admissions' %}" id="lnk_admissions">
      {% trans 'Enrolments' %}
    </a>
  </li>
  <li class="active">
    {% trans 'Continuing enrolment applications' %}
  </li>
{% endblock %}



{% block form_fields %}
  <div class="row">
    {% bootstrap_field filter_form.annee_academique form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.edition form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.numero form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.matricule_candidat form_group_class="form-group col-md-3" %}
    {% bootstrap_field filter_form.etats form_group_class="form-group col-md-3" %}
  </div>
  <div class="row">
    {% bootstrap_field filter_form.entites form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.types_formation form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.sigles_formations form_group_class="form-group col-md-4" %}
    {% bootstrap_field filter_form.inscription_requise form_group_class="form-group col-md-2" %}
    {% bootstrap_field filter_form.paye form_group_class="form-group col-md-2" %}
  </div>
  <div class="row">
    {% bootstrap_field filter_form.marque_d_interet form_group_class="form-group col-md-12" %}
  </div>

  <hr>
  <div>
    <div class="row flex-content no-space">
      <div class="col-md-4">
        {% bootstrap_field filter_form.liste_travail %}
      </div>
      <button id="toggle-checklist-filters" type="button" class="btn btn-link nopadding" value="off">
        {% translate "Show the states of the checklist" %}
      </button>
    </div>
    <div id="checklist-filters-container">
      <div class="btn-group mt-1" data-toggle="buttons" id="checklist-filters-mode">
        {% for choice in filter_form.mode_filtres_etats_checklist %}
          <label
            for="{{ choice.id_for_label  }}"
            class="btn btn-primary{% if filter_form.mode_filtres_etats_checklist.value == choice.data.value %} active{% endif %}"
          >
            {{ choice.tag }}
            {{ choice.choice_label }}
          </label>
        {% endfor %}
      </div>
      {% bootstrap_field filter_form.filtres_etats_checklist label='' form_group_class="form-group mt-1" %}
    </div>
  </div>
{% endblock %}

{% block script %}
  {{ block.super }}
  <script src="{% static 'js/clipboard.js' %}"></script>

  <script>
      $(document).ready(function () {
          initializePopover({ trigger: 'hover' })
          initializeLazyPopover()

          const $reference = $('#id_numero');
          $reference.mask(getReferenceMask($reference.val()), {
              translation: {
                  'S': { pattern: /[a-zA-Z]/, optional: true },
              },
              onKeyPress: function (cep, e, field, options) {
                  $reference.mask(getReferenceMask(cep), options);
              },
          });

          {# Working lists #}
          const stateInput = $('#id_etats');
          const typeInput = $('#id_type');
          const filterModeInputs = $('input[name="mode_filtres_etats_checklist"]');
          const checklistFiltersInputs = $('#checklist-filters-container .multi-widget input[type="checkbox"]');
          const toggleChecklistFiltersButton = $('#toggle-checklist-filters');
          let selectWorkListInProgress = false;

          {# Toggle the checklist filters #}
          toggleChecklistFiltersButton.on('click', function () {
              if ($(this).val() === 'off') {
                  $('#checklist-filters-container').show();
                  $(this).val('on');
                  $(this)[0].innerText = '{% translate "Hide the states of the checklist" %}';
              } else {
                  $('#checklist-filters-container').hide();
                  $(this).val('off');
                  $(this)[0].innerText = '{% translate "Show the states of the checklist" %}';
              }
          });

          toggleChecklistFiltersButton.val(checklistFiltersInputs.filter(':checked').length > 0 ? 'off' : 'on').trigger('click');

          $('#id_etats, #id_type, input[name="mode_filtres_etats_checklist"], #checklist-filters-container .multi-widget input[type="checkbox"]').on('change', function () {
              {# Reset the selected working list if the values of the dependent inputs change except if this change was triggered from the working list #}
              if (selectWorkListInProgress) return;
              $('#id_liste_travail').val('').trigger('change');
          });

          $('#id_liste_travail').on('select2:select', function (event) {
              {# When selecting a working list, update the dependent inputs #}
              const data = event.params.data;
              selectWorkListInProgress = true;

              stateInput.val(data.admission_statuses).trigger('change');
              typeInput.val([data.admission_type]).trigger('change');
              if (!data.checklist_filters_mode) {
                  filterModeInputs.filter(':checked').prop('checked', false).trigger('change');
                  filterModeInputs.parents('label').removeClass('active');
              } else {
                  filterModeInputs.filter(`[value="${data.checklist_filters_mode}"]`).trigger('click');
              }
              data.checklist_filters.forEach(function(value, index) {
                  checklistFiltersInputs.filter(`[name="filtres_etats_checklist_${index}"]`).val(value).trigger('change');
              });
              selectWorkListInProgress = false;
          });
      });
  </script>
{% endblock %}

{% block style %}
  {{ block.super }}

  <style>
    #checklist-filters-container .multi-widget {
      display: flex;
      flex-wrap: wrap;
      gap: 1em;
    }

    #checklist-filters-container .multi-widget label.control-label {
      text-decoration: underline;
    }

    #checklist-filters-container .multi-widget ul {
      list-style-type: none;
      padding-left: 0;
    }

    #checklist-filters-container .multi-widget label:not(.control-label) {
      font-weight: normal;
    }

    #checklist-filters-container .multi-widget input[value*="."] {
      margin-left: 2em;
    }

    #checklist-filters-container {
      display: none;
    }

    #checklist-filters-mode label:not(.active) {
      background-color: #ddd;
      border-color: #ddd;
      color: #337ab7;
    }
  </style>
{% endblock %}